# @package _group_
defaults:
    - experiment: cifar10
    - distributed: base
    - hydra/output: custom

parameter:
    epochs: 200
    linear_schedule: true
    metric: acc # loss or acc
    momentum: 0.9
    num_workers: 8
    seed: 7 # random seed value
    use_cuda: true
    warmup_epochs: 10
